In [40]:
from sklearn.preprocessing import MinMaxScaler

In [41]:
X = [[2, 1], [3, 1], [1, 4], [2, 6]]


In [42]:
# 归一化，区间设置为(-1,1)
print(MinMaxScaler(feature_range=(-1, 1)).fit_transform(X))

[[ 0.  -1. ]
 [ 1.  -1. ]
 [-1.   0.2]
 [ 0.   1. ]]


In [43]:
from sklearn.preprocessing import StandardScaler

In [44]:
# 标准化
print(StandardScaler().fit_transform(X))

[[ 0.         -0.94280904]
 [ 1.41421356 -0.94280904]
 [-1.41421356  0.47140452]
 [ 0.          1.41421356]]


In [45]:
import numpy as np

In [46]:
X = np.array(X)
print(X)

[[2 1]
 [3 1]
 [1 4]
 [2 6]]


In [47]:
mean = np.mean(X,axis=0)
print(np.mean(X,axis=0))

[2. 3.]


In [48]:
std = np.std(X,axis=0)
print(np.std(X,axis=0))

[0.70710678 2.12132034]


In [49]:
print((X-mean)/std)

[[ 0.         -0.94280904]
 [ 1.41421356 -0.94280904]
 [-1.41421356  0.47140452]
 [ 0.          1.41421356]]
