In [15]:
import numpy as np

In [16]:
A = np.array([[1, 1], [2, 2], [0, 0]])

In [17]:
U,S,V = np.linalg.svd(A)
print(U)
print(S)
print(V)


[[-0.4472136  -0.89442719  0.        ]
 [-0.89442719  0.4472136   0.        ]
 [ 0.          0.          1.        ]]
[3.16227766e+00 1.57009246e-16]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [18]:
from sklearn.utils.extmath import randomized_svd

In [19]:
U,S,V = randomized_svd(A, n_components=2)
print(U)
print(S)
print(V)


[[ 0.4472136   0.89442719]
 [ 0.89442719 -0.4472136 ]
 [ 0.         -0.        ]]
[3.16227766 0.        ]
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


In [20]:
from sklearn.decomposition import PCA
X = np.random.randn(100,3)
pca = PCA(n_components=2)
X_pca=pca.fit_transform(X)
print(X_pca.shape)

(100, 2)
